baseURL = "https://jacopofar.github.io/blog"
languageCode = "en-us"
title = "Hugo Site, WIP"
theme = "hugo-tranquilpeak-theme"
relativeurls = true
[params]
  [[params.customJS]]
    src = "js/piwik.js"
